# Logistic Regression

## Step1 - Importing all the required libraries

In [72]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay

import pickle

## Step2 - Loading the dataset using pandas

In [73]:
data=pd.read_csv(r"C:\Users\HP\Downloads\archive (15)\diabetes_prediction_dataset.csv")

In [74]:
print(data)

       gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19
1      Female  54.0             0              0         No Info  27.32
2        Male  28.0             0              0           never  27.32
3      Female  36.0             0              0         current  23.45
4        Male  76.0             1              1         current  20.14
...       ...   ...           ...            ...             ...    ...
99995  Female  80.0             0              0         No Info  27.32
99996  Female   2.0             0              0         No Info  17.37
99997    Male  66.0             0              0          former  27.83
99998  Female  24.0             0              0           never  35.42
99999  Female  57.0             0              0         current  22.43

       HbA1c_level  blood_glucose_level  diabetes
0              6.6                  140         0
1              6.6                   80         0
2              5.7                  158         0
3              5.0                  155         0
4              4.8                  155         0
...            ...                  ...       ...
99995          6.2                   90         0
99996          6.5                  100         0
99997          5.7                  155         0
99998          4.0                  100         0
99999          6.6                   90         0

[100000 rows x 9 columns]

## Step3 - Data Cleaning(Exploratory data analysis)

In [75]:
data.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [76]:
data.tail()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [77]:
data.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [78]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [79]:
data.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

## Step4 - Selecting which features must be taken as the dependent and the independent variable

In [80]:
X=data[['smoking_history','age','blood_glucose_level','HbA1c_level']]
Y=data['diabetes']

In [81]:
print(X)
print(Y)

      smoking_history   age  blood_glucose_level  HbA1c_level
0               never  80.0                  140          6.6
1             No Info  54.0                   80          6.6
2               never  28.0                  158          5.7
3             current  36.0                  155          5.0
4             current  76.0                  155          4.8
...               ...   ...                  ...          ...
99995         No Info  80.0                   90          6.2
99996         No Info   2.0                  100          6.5
99997          former  66.0                  155          5.7
99998           never  24.0                  100          4.0
99999         current  57.0                   90          6.6

[100000 rows x 4 columns]
0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 100000, dtype: int64

## Step6 - Using one hot encoding in order to convert the categorical variables into numerical

In [82]:
X=pd.get_dummies(X, columns=['smoking_history'],drop_first=True)

## Step 7 - Splitting the data into testing and training data

In [83]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

## Step8 - Importing Logistic Regression

In [84]:
classifier=LogisticRegression(class_weight='balanced')

## Step9 - Fitting the data in order to train the model

In [85]:
classifier.fit(X_train,Y_train)

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced')

## Step10 - Predicting the values

In [86]:
prediction=classifier.predict(X_test)

## Step11 - Evaluation of the model

In [87]:
from sklearn.metrics import (accuracy_score,precision_score,recall_score,f1_score)

In [88]:
print(f"\033[1mF1 Score:\033[0m", f1_score(Y_test, prediction))
print(f"\033[1mAccuracy:\033[0m", accuracy_score(Y_test, prediction))
print(f"\033[1mRecall:\033[0m",recall_score(Y_test,prediction))
print(f"\033[1mPrecision:\033[0m", precision_score(Y_test, prediction))

F1 Score: 0.5359166514348382
Accuracy: 0.87305
Recall: 0.8583138173302107
Precision: 0.38958277969705024

## Step12 - Converting this into the pkl file

In [112]:
with open("diabetes.pkl", "wb") as file:
    pickle.dump(classifier, file)
print("Model saved successfully")

Model saved successfully

## Step 13 - Import the GUI(Graphical User Interface) Libraries

In [113]:
!pip install customtkinter
import customtkinter as ctk

Requirement already satisfied: customtkinter in c:\users\hp\anaconda3\lib\site-packages (6.0.0)
Requirement already satisfied: darkdetect in c:\users\hp\anaconda3\lib\site-packages (from customtkinter) (0.8.0)
Requirement already satisfied: packaging in c:\users\hp\anaconda3\lib\site-packages (from customtkinter) (23.2)

## Step 13 - Load the saved model

In [114]:
with open("diabetes.pkl", "rb") as file:
    classifier = pickle.load(file)

## Step 14 - Create the window

In [115]:
ctk.set_appearance_mode("light")
ctk.set_default_color_theme("green")

app1 = ctk.CTk()

app1.geometry("1000x600")

app1.title("Diabetes Prediction")

''

## Step 15 - Add the title

In [116]:
title = ctk.CTkLabel(
    app1,
    text="🩺📊 Diabetes Prediction System",
    font=("Poppins",28,"bold"),
    text_color="#82074A"
)

title.pack(pady=20)

## Step 16 - Add the buttons

In [117]:
smoking = ctk.CTkEntry(
    app1,
    placeholder_text="Is the person a smoker?:",
    width=300,
    height=45
)
smoking.pack(pady=10)

HbA1c_level_ = ctk.CTkEntry(
    app1,
    placeholder_text="What is the person's haemoglobin level?:",
    width=300,
    height=45
)
HbA1c_level_.pack(pady=10)

blood_glucose = ctk.CTkEntry(
    app1,
    placeholder_text="What is the person's blood glucose level?:",
    width=300,
    height=45
)
blood_glucose.pack(pady=10)

In [118]:
age_value = ctk.CTkEntry(
    app1,
    placeholder_text="Enter the age of the person:",
    width=300,
    height=45
)

age_value.pack(pady=10)

## Step 17 - Add the prediction function

In [119]:
def predict():

    age= float(age_value.get())

    smoking_history = smoking.get().strip().lower()

    smoking_map = {
        "no info": 0,
        "current": 1,
        "ever": 2,
        "former": 3,
        "never": 4,
        "not current": 5
        }

    smoking_history = smoking_map[smoking_history]
    
    HbA1c_level= float(HbA1c_level_.get())

    blood_glucose_level= int(blood_glucose.get())
    
    data = np.array([[age,smoking_history,HbA1c_level,blood_glucose_level]])

    result = "Yes" if prediction[0] == 1 else "No"

    output.configure(text=f"Is the person having diabetes?\n{result}")

## Step 18 - Add the prediction button

In [120]:
output = ctk.CTkLabel(
    app1,
    text=" ",
    font=("Poppins",22,"bold"),
    text_color="#700535",
    fg_color="#E85291",
    corner_radius=12,
    width=300,
    height=80
)

output.pack(pady=20)

## Step 19 - Add the result label

In [121]:
button = ctk.CTkButton(
    app1,
    text="Predict Diabetes",
    command=predict,
    width=220,
    height=50,
    corner_radius=12,
    fg_color="#EA9D9D",
    hover_color="#EB5C60",
    text_color="#191414"
)

button.pack(pady=20)

## Step 20 - Run the app

In [123]:
app1.mainloop()